## exploring the metadata

In [1]:
import gzip
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

Matplotlib is building the font cache; this may take a moment.

### checking out what the metadata entails and where the matrix table begins

In [5]:
# checking out what the metadata entails and where the matrix table begins
with gzip.open("../data/GSE48350_series_matrix.txt.gz", "rt") as f:
    for i in range(100):
        print(f.readline())

!Series_title	"Alzheimer's Disease Dataset"

!Series_geo_accession	"GSE48350"

!Series_status	"Public on Apr 21 2014"

!Series_submission_date	"Jun 27 2013"

!Series_last_update_date	"May 03 2022"

!Series_pubmed_id	"18832152"

!Series_pubmed_id	"23273601"

!Series_pubmed_id	"22824372"

!Series_pubmed_id	"20838618"

!Series_pubmed_id	"23999428"

!Series_pubmed_id	"23206327"

!Series_summary	"This dataset contains microarray data from normal controls (aged 20-99 yrs) and Alzheimer's disease cases, from 4 brain regions: hippocampus, entorhinal cortex, superior frontal cortex, post-central gyrus.   Changes in expression of synaptic and immune related genes were analyzed, investigating age-related changes and AD-related changes, and  region-specific patterns of change."

!Series_summary	"These AD cases were processed simultaneously with the control cases (young and aged) included in GSE11882 (GSE11882 dataset contains data exclusively from normal control brains)."

!Series_overall_design	"Postmortem brain tissue was collected from ADRC brain banks. Cases were preferentially selected where 3 or more brain regions were available.  Cases labeled ""indiv"" refers to normal controls (young and aged), and AD cases are labeled ""AD"".  These AD cases were processed simultaneously with the control cases (young and aged) included in GSE11882 (GSE11882 dataset contains data exclusively from normal control brains)."

!Series_type	"Expression profiling by array"

!Series_contributor	"N,C,Berchtold"

!Series_contributor	"C,W,Cotman"

!Series_sample_id	"GSM300166 GSM300167 GSM300168 GSM300169 GSM300170 GSM300171 GSM300172 GSM300173 GSM300174 GSM300175 GSM300176 GSM300177 GSM300178 GSM300179 GSM300180 GSM300181 GSM300182 GSM300183 GSM300185 GSM300186 GSM300187 GSM300188 GSM300189 GSM300190 GSM300191 GSM300192 GSM300193 GSM300194 GSM300195 GSM300196 GSM300197 GSM300198 GSM300199 GSM300200 GSM300201 GSM300202 GSM300203 GSM300204 GSM300205 GSM300206 GSM300207 GSM300208 GSM300209 GSM300210 GSM300211 GSM300212 GSM300213 GSM300214 GSM300215 GSM300216 GSM300217 GSM300218 GSM300219 GSM300220 GSM300221 GSM300222 GSM300223 GSM300224 GSM300225 GSM300226 GSM300227 GSM300228 GSM300229 GSM300230 GSM300231 GSM300232 GSM300233 GSM300234 GSM300235 GSM300236 GSM300237 GSM300238 GSM300239 GSM300240 GSM300241 GSM300242 GSM300243 GSM300244 GSM300245 GSM300246 GSM300247 GSM300248 GSM300249 GSM300250 GSM300251 GSM300252 GSM300253 GSM300254 GSM300255 GSM300256 GSM300258 GSM300259 GSM300260 GSM300261 GSM300262 GSM300263 GSM300264 GSM300265 GSM300266 GSM300267 GSM300268 GSM300269 GSM300270 GSM300271 GSM300272 GSM300273 GSM300274 GSM300275 GSM300276 GSM300277 GSM300278 GSM300279 GSM300280 GSM300281 GSM300282 GSM300283 GSM300284 GSM300285 GSM300286 GSM300287 GSM300288 GSM300289 GSM300290 GSM300291 GSM300292 GSM300293 GSM300294 GSM300295 GSM300296 GSM300297 GSM300298 GSM300299 GSM300300 GSM300301 GSM300302 GSM300303 GSM300304 GSM300305 GSM300306 GSM300307 GSM300308 GSM300309 GSM300310 GSM300311 GSM300312 GSM300313 GSM300314 GSM300315 GSM300316 GSM300317 GSM300318 GSM300319 GSM300320 GSM300321 GSM300322 GSM300323 GSM300324 GSM300325 GSM300326 GSM300327 GSM300328 GSM300329 GSM300330 GSM300331 GSM300332 GSM300333 GSM300335 GSM300338 GSM300339 GSM300340 GSM300341 GSM318840 GSM350078 GSM1176196 GSM1176197 GSM1176198 GSM1176199 GSM1176200 GSM1176201 GSM1176202 GSM1176203 GSM1176204 GSM1176205 GSM1176206 GSM1176207 GSM1176208 GSM1176209 GSM1176210 GSM1176211 GSM1176212 GSM1176213 GSM1176214 GSM1176215 GSM1176216 GSM1176217 GSM1176218 GSM1176219 GSM1176220 GSM1176221 GSM1176222 GSM1176223 GSM1176224 GSM1176225 GSM1176226 GSM1176227 GSM1176228 GSM1176229 GSM1176230 GSM1176231 GSM1176232 GSM1176233 GSM1176234 GSM1176235 GSM1176236 GSM1176237 GSM1176238 GSM1176239 GSM1176240 GSM1176241 GSM1176242 GSM1176243 GSM1176244 GSM1176245 GSM1176246 GSM1176247 GSM1176248 GSM1176249 GSM1176250 GSM1176251 GSM1176252 GSM1176253 GSM1176254 GSM1176255 GSM1176256 GSM1176257 GSM1176258 GSM1176259 GSM1176260 GSM1176261 GSM1176262 GSM1176263 GSM1176264 GSM1176265 GSM1176266 GSM1176267 GSM1176268 GSM1176269 GSM1176270 GSM1176271 GSM1176272 GSM1176273 GSM1176274 GSM1176275 "

!Series_contact_name	"Nicole,Claudia,Berchtold"

!Series_contact_email	"nberchto@uci.edu"

!Series_contact_phone	"949 824 6071"

!Series_contact_laboratory	"Carl W. Cotman"

!Series_contact_department	"Institute for Memory Impairments and Neurological Disorders"

!Series_contact_institute	"UC Irvine"

!Series_contact_address	"1226 Gillespie Neuroscience Facility"

!Series_contact_city	"Irvine"

!Series_contact_state	"CA"

!Series_contact_zip/postal_code	"92697-4540"

!Series_contact_country	"USA"

!Series_supplementary_file	"ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE48nnn/GSE48350/suppl/GSE48350_RAW.tar"

!Series_platform_id	"GPL570"

!Series_platform_taxid	"9606"

!Series_sample_taxid	"9606"

!Series_relation	"BioProject: https://www.ncbi.nlm.nih.gov/bioproject/PRJNA209800"



!Sample_title	"PostcentralGyrus_female_91yrs_indiv10"	"SuperiorFrontalGyrus_female_91yrs_indiv10"	"Hippocampus_female_96yrs_indiv105"	"Hippocampus_male_82yrs_indiv106"	"Hippocampus_male_84yrs_indiv108"	"Hippocampus_female_87yrs_indiv109"	"Hippocampus_female_82yrs_indiv111"	"EntorhinalCortex_male_45yrs_indiv12"	"Hippocampus_male_45yrs_indiv12"	"PostcentralGyrus_male_45yrs_indiv12"	"SuperiorFrontalGyrus_male_45yrs_indiv12"	"EntorhinalCortex_male_95yrs_indiv14"	"Hippocampus_male_95yrs_indiv14"	"PostcentralGyrus_male_95yrs_indiv14"	"SuperiorFrontalGyrus_male_95yrs_indiv14"	"EntorhinalCortex_male_80yrs_indiv15"	"Hippocampus_male_80yrs_indiv15"	"PostcentralGyrus_male_80yrs_indiv15"	"Hippocampus_male_91yrs_indiv16-07"	"EntorhinalCortex_female_45yrs_indiv17"	"Hippocampus_female_45yrs_indiv17"	"SuperiorFrontalGyrus_female_45yrs_indiv17"	"EntorhinalCortex_female_74yrs_indiv18"	"Hippocampus_female_74yrs_indiv18"	"SuperiorFrontalGyrus_female_74yrs_indiv18"	"EntorhinalCortex_female_99yrs_indiv2"	"Hippocampus_female_99yrs_indiv2"	"PostcentralGyrus_female_99yrs_indiv2"	"SuperiorFrontalGyrus_female_99yrs_indiv2"	"EntorhinalCortex_female_74yrs_indiv21"	"Hippocampus_female_74yrs_indiv21"	"PostcentralGyrus_female_74yrs_indiv21"	"SuperiorFrontalGyrus_female_74yrs_indiv21"	"PostcentralGyrus_female_92yrs_indiv26"	"SuperiorFrontalGyrus_female_92yrs_indiv26"	"PostcentralGyrus_female_91yrs_indiv27"	"SuperiorFrontalGyrus_female_91yrs_indiv27"	"EntorhinalCortex_male_83yrs_indiv28"	"Hippocampus_male_83yrs_indiv28"	"PostcentralGyrus_male_83yrs_indiv28"	"SuperiorFrontalGyrus_male_83yrs_indiv28"	"EntorhinalCortex_male_28yrs_indiv29"	"Hippocampus_male_28yrs_indiv29"	"PostcentralGyrus_male_28yrs_indiv29"	"SuperiorFrontalGyrus_male_28yrs_indiv29"	"PostcentralGyrus_female_74yrs_indiv30"	"SuperiorFrontalGyrus_female_74yrs_indiv30"	"EntorhinalCortex_male_97yrs_indiv34"	"Hippocampus_male_97yrs_indiv34"	"PostcentralGyrus_male_97yrs_indiv34"	"SuperiorFrontalGyrus_male_97yrs_indiv34"	"EntorhinalCortex_female_34yrs_indiv35"	"Hippocampus_female_34yrs_indiv35"	"PostcentralGyrus_female_34yrs_indiv35"	"SuperiorFrontalGyrus_female_34yrs_indiv35"	"EntorhinalCortex_female_74yrs_indiv38"	"Hippocampus_female_74yrs_indiv38"	"PostcentralGyrus_female_74yrs_indiv38"	"SuperiorFrontalGyrus_female_74yrs_indiv38"	"PostcentralGyrus_female_90yrs_indiv40"	"Hippocampus_female_91yrs_indiv40-04"	"EntorhinalCortex_female_44yrs_indiv42"	"SuperiorFrontalGyrus_female_44yrs_indiv42"	"EntorhinalCortex_female_37yrs_indiv45"	"Hippocampus_female_37yrs_indiv45"	"PostcentralGyrus_female_37yrs_indiv45"	"SuperiorFrontalGyrus_female_37yrs_indiv45"	"EntorhinalCortex_male_85yrs_indiv46"	"Hippocampus_male_85yrs_indiv46"	"PostcentralGyrus_male_85yrs_indiv46"	"SuperiorFrontalGyrus_male_85yrs_indiv46"	"EntorhinalCortex_female_70yrs_indiv47"	"Hippocampus_female_70yrs_indiv47"	"PostcentralGyrus_female_70yrs_indiv47"	"SuperiorFrontalGyrus_female_70yrs_indiv47"	"EntorhinalCortex_female_64yrs_indiv52"	"Hippocampus_female_64yrs_indiv52"	"PostcentralGyrus_female_64yrs_indiv52"	"SuperiorFrontalGyrus_female_64yrs_indiv52"	"PostcentralGyrus_male_70yrs_indiv53"	"SuperiorFrontalGyrus_male_70yrs_indiv53"	"EntorhinalCortex_female_85yrs_indiv54"	"PostcentralGyrus_female_85yrs_indiv54"	"SuperiorFrontalGyrus_female_85yrs_indiv54"	"SuperiorFrontalGyrus_female_91yrs_indiv59"	"EntorhinalCortex_male_21yrs_indiv66"	"PostcentralGyrus_male_21yrs_indiv66"	"SuperiorFrontalGyrus_male_21yrs_indiv66"	"Hippocampus_male_69yrs_indiv67"	"PostcentralGyrus_male_69yrs_indiv67"	"EntorhinalCortex_male_40yrs_indiv68"	"PostcentralGyrus_male_40yrs_indiv68"	"SuperiorFrontalGyrus_male_40yrs_indiv68"	"EntorhinalCortex_male_52yrs_indiv71"	"Hippocampus_male_52yrs_indiv71"	"PostcentralGyrus_male_52yrs_indiv71"	"SuperiorFrontalGyrus_male_52yrs_indiv71"	"PostcentralGyrus_male_75yrs_indiv72"	"SuperiorFrontalGyrus_male_75yrs_indiv72"	"EntorhinalCortex_male_86yrs_indiv73"	"Hippocampus_male_86yrs_indiv73"	"PostcentralGyrus_male_86yrs_indiv73"	"SuperiorFrontalGyrus_male_86yrs_indiv73"	"EntorhinalCortex_female_26yrs_indiv76"	"Hippocampus_female_26yrs_indiv76"	"PostcentralGyrus_female_26yrs_indiv76"	"SuperiorFrontalGyrus_female_26yrs_indiv76"	"EntorhinalCortex_male_20yrs_indiv77"	"Hippocampus_male_20yrs_indiv77"	"PostcentralGyrus_male_20yrs_indiv77"	"SuperiorFrontalGyrus_male_20yrs_indiv77"	"EntorhinalCortex_male_20yrs_indiv78"	"Hippocampus_male_20yrs_indiv78"	"PostcentralGyrus_male_20yrs_indiv78"	"SuperiorFrontalGyrus_male_20yrs_indiv78"	"PostcentralGyrus_female_36yrs_indiv79"	"SuperiorFrontalGyrus_female_36yrs_indiv79"	"EntorhinalCortex_male_69yrs_indiv8"	"Hippocampus_male_69yrs_indiv8"	"PostcentralGyrus_male_69yrs_indiv8"	"SuperiorFrontalGyrus_male_69yrs_indiv8"	"EntorhinalCortex_female_44yrs_indiv80"	"Hippocampus_female_44yrs_indiv80"	"PostcentralGyrus_female_44yrs_indiv80"	"SuperiorFrontalGyrus_female_44yrs_indiv80"	"EntorhinalCortex_female_48yrs_indiv81"	"Hippocampus_female_48yrs_indiv81"	"PostcentralGyrus_female_48yrs_indiv81"	"SuperiorFrontalGyrus_female_48yrs_indiv81"	"EntorhinalCortex_female_30yrs_indiv82"	"Hippocampus_female_30yrs_indiv82"	"SuperiorFrontalGyrus_female_30yrs_indiv82"	"EntorhinalCortex_male_20yrs_indiv83"	"Hippocampus_male_20yrs_indiv83"	"PostcentralGyrus_male_20yrs_indiv83"	"SuperiorFrontalGyrus_male_20yrs_indiv83"	"EntorhinalCortex_male_33yrs_indiv84"	"Hippocampus_male_33yrs_indiv84"	"PostcentralGyrus_male_33yrs_indiv84"	"SuperiorFrontalGyrus_male_33yrs_indiv84"	"EntorhinalCortex_male_22yrs_indiv85"	"Hippocampus_male_22yrs_indiv85"	"PostcentralGyrus_male_22yrs_indiv85"	"SuperiorFrontalGyrus_male_22yrs_indiv85"	"EntorhinalCortex_male_42yrs_indiv86"	"Hippocampus_male_42yrs_indiv86"	"PostcentralGyrus_male_42yrs_indiv86"	"SuperiorFrontalGyrus_male_42yrs_indiv86"	"EntorhinalCortex_male_45yrs_indiv87"	"Hippocampus_male_45yrs_indiv87"	"PostcentralGyrus_male_45yrs_indiv87"	"SuperiorFrontalGyrus_male_45yrs_indiv87"	"EntorhinalCortex_female_47yrs_indiv88"	"Hippocampus_female_47yrs_indiv88"	"PostcentralGyrus_female_47yrs_indiv88"	"SuperiorFrontalGyrus_female_47yrs_indiv88"	"EntorhinalCortex_male_69yrs_indiv93"	"Hippocampus_male_69yrs_indiv93"	"PostcentralGyrus_male_69yrs_indiv93"	"SuperiorFrontalGyrus_male_69yrs_indiv93"	"EntorhinalCortex_female_91yrs_indiv94"	"Hippocampus_female_91yrs_indiv94"	"PostcentralGyrus_female_91yrs_indiv94"	"SuperiorFrontalGyrus_female_91yrs_indiv94"	"EntorhinalCortex_male_75yrs_indiv96"	"Hippocampus_male_75yrs_indiv96"	"SuperiorFrontalGyrus_male_75yrs_indiv96"	"EntorhinalCortex_female_82yrs_indiv98"	"Hippocampus_female_82yrs_indiv98"	"PostcentralGyrus_female_82yrs_indiv98"	"SuperiorFrontalGyrus_female_82yrs_indiv98"	"SuperiorFrontalGyrus_male_66yrs_indiv63"	"SuperiorFrontalGyrus_male_80yrs_indiv15"	"entorhinal cortex_female_76_AD_48"	"entorhinal cortex_female_86_AD_15"	"entorhinal cortex_female_82_AD_9"	"entorhinal cortex_female_85_AD_24"	"entorhinal cortex_female_90_AD_36"	"entorhinal cortex_female_90_AD_6"	"entorhinal cortex_female_90_AD_75"	"entorhinal cortex_female_91_AD_11"	"entorhinal cortex_male_76_AD_69"	"entorhinal cortex_male_85_AD_51"	"entorhinal cortex_male_85_AD_74"	"entorhinal cortex_male_86_AD_92"	"entorhinal cortex_male_87_AD_19"	"entorhinal cortex_male_94_AD_5"	"entorhinal cortex_male_94_AD_90"	"hippocampus_female_60_AD_20"	"hippocampus_female_74_AD_37"	"hippocampus_female_76_AD_48"	"hippocampus_female_79_AD_16"	"hippocampus_female_86_AD_15"	"hippocampus_female_85_AD_24"	"hippocampus_female_90_AD_23"	"hippocampus_female_90_AD_36"	"hippocampus_female_90_AD_75"	"hippocampus_female_91_AD_11"	"hippocampus_male_76_AD_33"	"hippocampus_male_76_AD_69"	"hippocampus_male_79_AD_7"	"hippocampus_male_80_AD_43"	"hippocampus_male_85_AD_51"	"hippocampus_male_86_AD_92"	"hippocampus_male_87_AD_19"	"hippocampus_male_94_AD_5"	"hippocampus_male_94_AD_90"	"post-central gyrus_female_60_AD_20"	"post-central gyrus_female_74_AD_37"	"post-central gyrus_female_76_AD_48"	"post-central gyrus_female_86_AD_15"	"post-central gyrus_female_82_AD_13"	"post-central gyrus_female_82_AD_9"	"post-central gyrus_female_85_AD_24"	"post-central gyrus_female_85_AD_57"	"post-central gyrus_female_90_AD_23"	"post-central gyrus_female_90_AD_36"	"post-central gyrus_female_90_AD_6"	"post-central gyrus_female_90_AD_75"	"post-central gyrus_female_91_AD_11"	"post-central gyrus_female_94_AD_70"	"post-central gyrus_female_95_AD_64"	"post-central gyrus_male_76_AD_33"	"post-central gyrus_male_76_AD_69"	"post-central gyrus_male_79_AD_7"	"post-central gyrus_male_85_AD_51"	"post-central gyrus_male_85_AD_74"	"post-central gyrus_male_86_AD_92"	"post-central gyrus_male_87_AD_19"	"post-central gyrus_male_94_AD_44"	"post-central gyrus_male_94_AD_5"	"post-central gyrus_male_94_AD_90"	"superior frontal gyrus_female_74_AD_37"	"superior frontal gyrus_female_76_AD_48"	"superior frontal gyrus_female_86_AD_15"	"superior frontal gyrus_female_82_AD_9"	"superior frontal gyrus_female_85_AD_24"	"superior frontal gyrus_female_85_AD_57"	"superior frontal gyrus_female_88_AD_91"	"superior frontal gyrus_female_90_AD_23"	"superior frontal gyrus_female_90_AD_36"	"superior frontal gyrus_female_90_AD_6"	"superior frontal gyrus_female_90_AD_75"	"superior frontal gyrus_female_91_AD_11"	"superior frontal gyrus_female_94_AD_70"	"superior frontal gyrus_female_95_AD_64"	"superior frontal gyrus_male_76_AD_33"	"superior frontal gyrus_male_85_AD_51"	"superior frontal gyrus_male_85_AD_74"	"superior frontal gyrus_male_86_AD_92"	"superior frontal gyrus_male_94_AD_44"	"superior frontal gyrus_male_94_AD_5"	"superior frontal gyrus_male_94_AD_90"

!Sample_geo_accession	"GSM300166"	"GSM300167"	"GSM300168"	"GSM300169"	"GSM300170"	"GSM300171"	"GSM300172"	"GSM300173"	"GSM300174"	"GSM300175"	"GSM300176"	"GSM300177"	"GSM300178"	"GSM300179"	"GSM300180"	"GSM300181"	"GSM300182"	"GSM300183"	"GSM300185"	"GSM300186"	"GSM300187"	"GSM300188"	"GSM300189"	"GSM300190"	"GSM300191"	"GSM300192"	"GSM300193"	"GSM300194"	"GSM300195"	"GSM300196"	"GSM300197"	"GSM300198"	"GSM300199"	"GSM300200"	"GSM300201"	"GSM300202"	"GSM300203"	"GSM300204"	"GSM300205"	"GSM300206"	"GSM300207"	"GSM300208"	"GSM300209"	"GSM300210"	"GSM300211"	"GSM300212"	"GSM300213"	"GSM300214"	"GSM300215"	"GSM300216"	"GSM300217"	"GSM300218"	"GSM300219"	"GSM300220"	"GSM300221"	"GSM300222"	"GSM300223"	"GSM300224"	"GSM300225"	"GSM300226"	"GSM300227"	"GSM300228"	"GSM300229"	"GSM300230"	"GSM300231"	"GSM300232"	"GSM300233"	"GSM300234"	"GSM300235"	"GSM300236"	"GSM300237"	"GSM300238"	"GSM300239"	"GSM300240"	"GSM300241"	"GSM300242"	"GSM300243"	"GSM300244"	"GSM300245"	"GSM300246"	"GSM300247"	"GSM300248"	"GSM300249"	"GSM300250"	"GSM300251"	"GSM300252"	"GSM300253"	"GSM300254"	"GSM300255"	"GSM300256"	"GSM300258"	"GSM300259"	"GSM300260"	"GSM300261"	"GSM300262"	"GSM300263"	"GSM300264"	"GSM300265"	"GSM300266"	"GSM300267"	"GSM300268"	"GSM300269"	"GSM300270"	"GSM300271"	"GSM300272"	"GSM300273"	"GSM300274"	"GSM300275"	"GSM300276"	"GSM300277"	"GSM300278"	"GSM300279"	"GSM300280"	"GSM300281"	"GSM300282"	"GSM300283"	"GSM300284"	"GSM300285"	"GSM300286"	"GSM300287"	"GSM300288"	"GSM300289"	"GSM300290"	"GSM300291"	"GSM300292"	"GSM300293"	"GSM300294"	"GSM300295"	"GSM300296"	"GSM300297"	"GSM300298"	"GSM300299"	"GSM300300"	"GSM300301"	"GSM300302"	"GSM300303"	"GSM300304"	"GSM300305"	"GSM300306"	"GSM300307"	"GSM300308"	"GSM300309"	"GSM300310"	"GSM300311"	"GSM300312"	"GSM300313"	"GSM300314"	"GSM300315"	"GSM300316"	"GSM300317"	"GSM300318"	"GSM300319"	"GSM300320"	"GSM300321"	"GSM300322"	"GSM300323"	"GSM300324"	"GSM300325"	"GSM300326"	"GSM300327"	"GSM300328"	"GSM300329"	"GSM300330"	"GSM300331"	"GSM300332"	"GSM300333"	"GSM300335"	"GSM300338"	"GSM300339"	"GSM300340"	"GSM300341"	"GSM318840"	"GSM350078"	"GSM1176196"	"GSM1176197"	"GSM1176198"	"GSM1176199"	"GSM1176200"	"GSM1176201"	"GSM1176202"	"GSM1176203"	"GSM1176204"	"GSM1176205"	"GSM1176206"	"GSM1176207"	"GSM1176208"	"GSM1176209"	"GSM1176210"	"GSM1176211"	"GSM1176212"	"GSM1176213"	"GSM1176214"	"GSM1176215"	"GSM1176216"	"GSM1176217"	"GSM1176218"	"GSM1176219"	"GSM1176220"	"GSM1176221"	"GSM1176222"	"GSM1176223"	"GSM1176224"	"GSM1176225"	"GSM1176226"	"GSM1176227"	"GSM1176228"	"GSM1176229"	"GSM1176230"	"GSM1176231"	"GSM1176232"	"GSM1176233"	"GSM1176234"	"GSM1176235"	"GSM1176236"	"GSM1176237"	"GSM1176238"	"GSM1176239"	"GSM1176240"	"GSM1176241"	"GSM1176242"	"GSM1176243"	"GSM1176244"	"GSM1176245"	"GSM1176246"	"GSM1176247"	"GSM1176248"	"GSM1176249"	"GSM1176250"	"GSM1176251"	"GSM1176252"	"GSM1176253"	"GSM1176254"	"GSM1176255"	"GSM1176256"	"GSM1176257"	"GSM1176258"	"GSM1176259"	"GSM1176260"	"GSM1176261"	"GSM1176262"	"GSM1176263"	"GSM1176264"	"GSM1176265"	"GSM1176266"	"GSM1176267"	"GSM1176268"	"GSM1176269"	"GSM1176270"	"GSM1176271"	"GSM1176272"	"GSM1176273"	"GSM1176274"	"GSM1176275"


In [6]:
with gzip.open("../data/GSE48350_series_matrix.txt.gz", "rt") as f:
    for i, line in enumerate(f):
        if line.startswith("!series_matrix_table_begin"):
            print("found at line", i)
            print(line[:200])
            break

found at line 78
!series_matrix_table_begin

In [7]:
# exploring the matrix table now
with gzip.open("../data/GSE48350_series_matrix.txt.gz", "rt") as f:
    lines = f.readlines()

start = 79

for i in range(start, start + 10):
    print(lines[i][:300])

"ID_REF"	"GSM300166"	"GSM300167"	"GSM300168"	"GSM300169"	"GSM300170"	"GSM300171"	"GSM300172"	"GSM300173"	"GSM300174"	"GSM300175"	"GSM300176"	"GSM300177"	"GSM300178"	"GSM300179"	"GSM300180"	"GSM300181"	"GSM300182"	"GSM300183"	"GSM300185"	"GSM300186"	"GSM300187"	"GSM300188"	"GSM300189"	"GSM300190"	"GS
"1007_s_at"	0.88801616	1.4355185	1.6096015	1.7549602	1.82073	1.439672	1.5876412	0.52471024	0.79657006	0.596087	0.7974215	0.80424404	1.7385257	0.87376684	1.4254059	1.2333348	1.2828906	0.94979066	1.5238266	3.2637012	2.555875	1.6712688	1.3596612	1.5937574	1.0457019	0.7809905	2.040923	0.79126626	1.32393
"1053_at"	0.6664604	0.8858521	1.8590777	1.0366664	1.421393	1.4850354	1.1862923	0.8766241	0.91771597	1.0181772	1.1045258	0.9100512	0.8454441	0.95510226	0.95193666	0.81050044	0.84245175	0.85325354	1.1592096	1.002131	0.7526203	0.986668	0.6623467	0.60956824	0.73762316	0.81134135	0.80686206	1.171593	1.00
"117_at"	0.8596384	1.0620298	3.0973945	2.2436552	5.0603013	13.800817	2.211287	0.824494	1.6506448	0.72315234	0.82068306	0.78828067	3.0418363	0.96156824	0.8110385	0.99393237	1.2870414	0.95443046	2.893376	0.97211105	1.3078353	1.4873922	10.866475	36.72309	1.4790733	1.0202985	2.433572	0.6249697	0.960078
"121_at"	0.9751495	1.0507448	0.9822838	1.1982367	1.0395293	0.781454	1.0119104	1.1515149	0.960083	0.90889245	1.1698936	1.0607997	0.8500785	0.7657404	0.7299446	1.0191907	1.116842	1.0726159	0.7926413	1.1334227	0.8566549	0.75921106	1.0500557	0.9802179	0.81910825	0.92332125	0.7788866	0.7513245	0.70686597
"1255_g_at"	0.49125472	0.5375254	3.1796446	1.5142903	2.185801	3.5416439	2.2131257	1.4224472	5.011413	1.3302159	0.5711281	0.8182494	0.9113392	0.4638748	0.522659	1.0579156	1.1003786	0.48046273	2.203428	1.0453261	1.0068681	0.56827545	0.8030625	0.943408	0.52716076	1.5200443	1.0502864	0.4812791	0.5206514
"1294_at"	0.8344268	0.929189	1.5193694	1.5570885	1.6412625	1.026549	2.3010652	0.78226674	1.0053184	0.8813058	0.9676111	1.0112987	1.0360056	0.7822554	0.96761113	1.0463039	1.2215087	0.76600957	1.813411	1.90987	1.7617314	1.1475486	0.83422786	0.99868655	0.9120756	1.008799	1.2519702	0.9674286	1.1813391	0
"1316_at"	1.6511366	1.0135372	0.580581	0.60882705	0.724664	0.505103	0.87266403	1.292927	0.8029462	0.95452017	0.9151795	1.2293415	0.78266984	0.9057088	0.76342255	1.1448379	0.9222442	1.6095423	1.005573	1.6114047	1.0405542	1.3337344	1.9031802	0.9701898	1.1656339	1.1618515	0.75744236	0.78433055	0.832325
"1320_at"	0.9306214	0.7651289	0.49654773	0.4568232	0.38591293	0.47090945	0.5370153	0.76090944	1.0732	0.9131874	0.787805	0.9454823	1.2681774	0.95089585	0.89140296	0.8693575	1.2657216	1.0267797	0.38362512	1.291321	0.94915694	0.77469397	0.9844069	1.4733579	0.7985419	1.4596648	2.0972166	0.99418634	0.763
"1405_i_at"	1.5584053	0.82681346	1.7416698	1.1630075	0.9058549	1.0794247	2.061148	1.0571477	1.1503546	0.7908079	1.0233426	1.0398523	0.97616506	0.8440265	1.648972	1.7719585	1.1624367	0.9852269	1.2089871	1.7400129	1.0287117	1.1589876	1.018126	0.99278075	0.9609933	1.2385424	0.8800687	0.7933478	0.904326

In [8]:
# extracting the matrix from the file
expression = pd.read_csv(
    "../data/GSE48350_series_matrix.txt.gz",
    sep="\t",
    skiprows=79,
    compression = "gzip",
)

expression.head()

,ID_REF,GSM300166,GSM300167,GSM300168,GSM300169,GSM300170,GSM300171,GSM300172,GSM300173,GSM300174,...,GSM1176266,GSM1176267,GSM1176268,GSM1176269,GSM1176270,GSM1176271,GSM1176272,GSM1176273,GSM1176274,GSM1176275
0,1007_s_at,0.888016,1.435518,1.609601,1.754960,1.820730,1.439672,1.587641,0.524710,0.796570,...,1.028650,0.774286,1.337073,1.244907,2.087099,0.959862,1.441913,0.904624,0.669172,0.713999
1,1053_at,0.666460,0.885852,1.859078,1.036666,1.421393,1.485035,1.186292,0.876624,0.917716,...,1.044734,0.789405,0.838707,0.825675,1.004600,0.936117,1.000000,0.834758,1.122123,1.202849
2,117_at,0.859638,1.062030,3.097395,2.243655,5.060301,13.800817,2.211287,0.824494,1.650645,...,0.931451,1.903424,1.452228,1.548969,1.064989,0.948225,0.825223,1.081357,1.489901,1.476950
3,121_at,0.975150,1.050745,0.982284,1.198237,1.039529,0.781454,1.011910,1.151515,0.960083,...,0.980565,1.152982,1.000000,0.594645,1.024383,1.140066,0.577931,1.156676,0.861224,1.128132
4,1255_g_at,0.491255,0.537525,3.179645,1.514290,2.185801,3.541644,2.213126,1.422447,5.011413,...,0.560050,0.554573,0.613756,0.521582,0.530901,0.548742,0.458067,0.552341,0.474526,0.559091

In [9]:
expression.columns[:10]

Index(['ID_REF', 'GSM300166', 'GSM300167', 'GSM300168', 'GSM300169',
       'GSM300170', 'GSM300171', 'GSM300172', 'GSM300173', 'GSM300174'],
      dtype='str')

In [10]:
# checking which brain regions each sample corresponds to
with gzip.open("../data/GSE48350_series_matrix.txt.gz", "rt") as f:
    for i, line in enumerate(f):
        if line.startswith("!Sample_title"):
            print("found at line", i)
            print(line[:1000])
            break

found at line 35
!Sample_title	"PostcentralGyrus_female_91yrs_indiv10"	"SuperiorFrontalGyrus_female_91yrs_indiv10"	"Hippocampus_female_96yrs_indiv105"	"Hippocampus_male_82yrs_indiv106"	"Hippocampus_male_84yrs_indiv108"	"Hippocampus_female_87yrs_indiv109"	"Hippocampus_female_82yrs_indiv111"	"EntorhinalCortex_male_45yrs_indiv12"	"Hippocampus_male_45yrs_indiv12"	"PostcentralGyrus_male_45yrs_indiv12"	"SuperiorFrontalGyrus_male_45yrs_indiv12"	"EntorhinalCortex_male_95yrs_indiv14"	"Hippocampus_male_95yrs_indiv14"	"PostcentralGyrus_male_95yrs_indiv14"	"SuperiorFrontalGyrus_male_95yrs_indiv14"	"EntorhinalCortex_male_80yrs_indiv15"	"Hippocampus_male_80yrs_indiv15"	"PostcentralGyrus_male_80yrs_indiv15"	"Hippocampus_male_91yrs_indiv16-07"	"EntorhinalCortex_female_45yrs_indiv17"	"Hippocampus_female_45yrs_indiv17"	"SuperiorFrontalGyrus_female_45yrs_indiv17"	"EntorhinalCortex_female_74yrs_indiv18"	"Hippocampus_female_74yrs_indiv18"	"SuperiorFrontalGyrus_female_74yrs_indiv18"	"EntorhinalCortex_female_99yrs_indiv2"	"H

In [11]:
# checking which samples are control vs alzheimers
with gzip.open("../data/GSE48350_series_matrix.txt.gz", "rt") as f:
    for i, line in enumerate(f):
        if line.startswith("!Sample_characteristics"):
            print("found at line", i)
            print(line[:1000])

found at line 44
!Sample_characteristics_ch1	"individual: 10, C"	"individual: 10, C"	"individual: 105, C"	"individual: 106, C"	"individual: 108, C"	"individual: 109, C"	"individual: 111, C"	"individual: 12, AA"	"individual: 12, AA"	"individual: 12, AA"	"individual: 12, AA"	"individual: 14, C"	"individual: 14, C"	"individual: 14, C"	"individual: 14, C"	"individual: 15, C"	"individual: 15, C"	"individual: 15, C"	"individual: 16-07, C"	"individual: 17, C"	"individual: 17, C"	"individual: 17, C"	"individual: 18, C"	"individual: 18, C"	"individual: 18, C"	"individual: 2, C"	"individual: 2, C"	"individual: 2, C"	"individual: 2, C"	"individual: 21, C"	"individual: 21, C"	"individual: 21, C"	"individual: 21, C"	"individual: 26, C"	"individual: 26, C"	"individual: 27, C"	"individual: 27, C"	"individual: 28, C"	"individual: 28, C"	"individual: 28, C"	"individual: 28, C"	"individual: 29, C"	"individual: 29, C"	"individual: 29, C"	"individual: 29, C"	"individual: 30, C"	"individual: 30, C"	"individual: 34, C"	"ind
found at line 45
!Sample_characteristics_ch1	"brain region: postcentral gyrus"	"brain region: superior frontal gyrus"	"brain region: hippocampus"	"brain region: hippocampus"	"brain region: hippocampus"	"brain region: hippocampus"	"brain region: hippocampus"	"brain region: entorhinal cortex"	"brain region: hippocampus"	"brain region: postcentral gyrus"	"brain region: superior frontal gyrus"	"brain region: entorhinal cortex"	"brain region: hippocampus"	"brain region: postcentral gyrus"	"brain region: superior frontal gyrus"	"brain region: entorhinal cortex"	"brain region: hippocampus"	"brain region: postcentral gyrus"	"brain region: hippocampus"	"brain region: entorhinal cortex"	"brain region: hippocampus"	"brain region: superior frontal gyrus"	"brain region: entorhinal cortex"	"brain region: hippocampus"	"brain region: superior frontal gyrus"	"brain region: entorhinal cortex"	"brain region: hippocampus"	"brain region: postcentral gyrus"	"brain region: superior frontal gyrus"	"brain region: entorhinal co
found at line 46
!Sample_characteristics_ch1	"gender: female"	"gender: female"	"gender: female"	"gender: male"	"gender: male"	"gender: female"	"gender: female"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: female"	"gender: female"	"gender: male"	"gender: male"	"gender: male"	"gender: male"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gender: female"	"gen
found at line 47
!Sample_characteristics_ch1	"age (yrs): 91"	"age (yrs): 91"	"age (yrs): 96"	"age (yrs): 82"	"age (yrs): 84"	"age (yrs): 87"	"age (yrs): 82"	"age (yrs): 45"	"age (yrs): 45"	"age (yrs): 45"	"age (yrs): 45"	"age (yrs): 95"	"age (yrs): 95"	"age (yrs): 95"	"age (yrs): 95"	"age (yrs): 80"	"age (yrs): 80"	"age (yrs): 80"	"age (yrs): 91"	"age (yrs): 45"	"age (yrs): 45"	"age (yrs): 45"	"age (yrs): 74"	"age (yrs): 74"	"age (yrs): 74"	"age (yrs): 99"	"age (yrs): 99"	"age (yrs): 99"	"age (yrs): 99"	"age (yrs): 74"	"age (yrs): 74"	"age (yrs): 74"	"age (yrs): 74"	"age (yrs): 92"	"age (yrs): 92"	"age (yrs): 91"	"age (yrs): 91"	"age (yrs): 83"	"age (yrs): 83"	"age (yrs): 83"	"age (yrs): 83"	"age (yrs): 28"	"age (yrs): 28"	"age (yrs): 28"	"age (yrs): 28"	"age (yrs): 74"	"age (yrs): 74"	"age (yrs): 97"	"age (yrs): 97"	"age (yrs): 97"	"age (yrs): 97"	"age (yrs): 34"	"age (yrs): 34"	"age (yrs): 34"	"age (yrs): 34"	"age (yrs): 74"	"age (yrs): 74"	"age (yrs): 74"	"age (yrs): 74"	"age (yrs): 90"	"age (yrs):
found at line 48
!Sample_characteristics_ch1	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	"apoe genotype: 3,3"	"apoe genotype: 4,4"	"apoe genotype: 3,4"	"apoe genotype: 3,4"	"apoe genotype: 3,4"	"apoe genotype: 3,4"	"apoe genotype: 4,4"	"apoe genotype: 4,4"	"apoe genotype: 4,4"	"apoe genotype: 3,3"	"apoe genotype: 3,4"	"apoe genotype: 3,3"	"apoe genotype: 3,4"	"apoe genotype: 3,3"	"apoe genotype: 3,3"	"apoe genotype: 3,4"	"apoe genotype: 2,4"	"apoe genotype: 3,3"	"apoe genotype: 3,4"	"apoe genotype: 4,4"	"apoe genotype: 3,4"	"apoe genoty
found at line 49
!Sample_characteristics_ch1	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	""	"mmse: 3"	"mmse: 9"	"mmse: 0"	"mmse: 26"	"mmse: 17"	"mmse: 20"	"mmse: no info"	"mmse: 11"	"mmse: no info"	"mmse: 22"	"mmse: no info"	"mmse: 19"	"mmse: 12"	"mmse: 15"	"mmse: no info"	"mmse: 12"	"mmse: 17"	"mmse: 3"	"mmse: 0"	"mmse: 9"	"mmse: 26"	"mmse: 12"	"mmse: 17"	"mmse: no info"	"mmse: 11"	"mmse: 0"	"mmse: no info"	"mmse: 6"	"mmse: 23"	"mmse: 22"	"mmse: 19"	"mmse: 12"	"mmse: 15"	"mmse: no info"	"mmse: 12"	"mmse: 17"	"mmse: 3"	"mmse: 9"	"mmse: 4"

In [12]:
with gzip.open("../data/GSE48350_series_matrix.txt.gz", "rt") as f:
    for line in f:
        if line.startswith("!Sample_title"):
            sample_line = line
            break

print("contains 'indiv':", "indiv" in sample_line)
print("contains 'AD':", "AD" in sample_line)

contains 'indiv': True
contains 'AD': True

In [13]:
sample_line.count("indiv")

173

## Building our first metadata table now

In [14]:
import gzip

sample_ids = expression.columns[1:]

with gzip.open("../data/GSE48350_series_matrix.txt.gz", "rt") as f:
    lines = f.readlines()

sample_title_line = lines[35]
titles = sample_title_line.strip().split("\t")[1:]

print("no of titles:", len(titles))
print()

for title in titles[:10]:
    print(title)

no of titles: 253

"PostcentralGyrus_female_91yrs_indiv10"
"SuperiorFrontalGyrus_female_91yrs_indiv10"
"Hippocampus_female_96yrs_indiv105"
"Hippocampus_male_82yrs_indiv106"
"Hippocampus_male_84yrs_indiv108"
"Hippocampus_female_87yrs_indiv109"
"Hippocampus_female_82yrs_indiv111"
"EntorhinalCortex_male_45yrs_indiv12"
"Hippocampus_male_45yrs_indiv12"
"PostcentralGyrus_male_45yrs_indiv12"

In [15]:
metadata = pd.DataFrame({
    "sample_ids": sample_ids,
    "titles": titles
})
metadata.head()

  sample_ids                                       titles
0  GSM300166      "PostcentralGyrus_female_91yrs_indiv10"
1  GSM300167  "SuperiorFrontalGyrus_female_91yrs_indiv10"
2  GSM300168          "Hippocampus_female_96yrs_indiv105"
3  GSM300169            "Hippocampus_male_82yrs_indiv106"
4  GSM300170            "Hippocampus_male_84yrs_indiv108"

In [18]:
# adding disease status
metadata["disease"] = metadata["titles"].apply(
    lambda x: "AD" if "AD" in x else "control"
)
metadata["disease"].value_counts()

disease
control    173
AD          80
Name: count, dtype: int64

In [ ]:
metadata.head()

  sample_ids                                       titles  disease
0  GSM300166      "PostcentralGyrus_female_91yrs_indiv10"  control
1  GSM300167  "SuperiorFrontalGyrus_female_91yrs_indiv10"  control
2  GSM300168          "Hippocampus_female_96yrs_indiv105"  control
3  GSM300169            "Hippocampus_male_82yrs_indiv106"  control
4  GSM300170            "Hippocampus_male_84yrs_indiv108"  control

In [21]:
expression.shape

(54676, 254)